# Generated by Django 4.2.4 on 2023-08-07 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='email',
            new_name='mail_id',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='address',
            field=models.TextField(default=1234),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useraccount',
            name='gender',
            field=models.TextField(choices=[('male', 'Male'), ('female', 'Female'), ('transgender', 'Transgender')], default=4567),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useraccount',
            name='materials',
            field=models.TextField(choices=[('debit', 'Debit Card'), ('credit', 'Credit Card'), ('cheque', 'Chequebook')], default=8976),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useraccount',
            name='phone_number',
            field=models.CharField(default=2345, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='branch',
            field=models.TextField(choices=[('aluva', 'Aluva'), ('edapally', 'edapally'), ('angamaly', 'Angamaly'), ('paravur', 'Paravur')]),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='district',
            field=models.TextField(verbose_name=[('ernakulam', 'Ernamkulam'), ('thrissur', 'Thrissur'), ('kottayam', 'Kottayam'), ('alappuzha', 'Alappuzha'), ('idukki', 'Idukki')]),
        ),
    ]
