# Generated by Django 4.2.4 on 2023-08-07 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0002_rename_email_useraccount_mail_id_useraccount_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='account_type',
            field=models.TextField(choices=[('savings', 'Savings'), ('current', 'Current')]),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='district',
            field=models.TextField(choices=[('ernakulam', 'Ernamkulam'), ('thrissur', 'Thrissur'), ('kottayam', 'Kottayam'), ('alappuzha', 'Alappuzha'), ('idukki', 'Idukki')]),
        ),
    ]
