# Generated by Django 4.2.4 on 2023-08-07 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0003_alter_useraccount_account_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='mail_id',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
